### ISSUE TITLE
undefined method `[]' for nil:NilClass with sprockets-rails 3.0.0

### ISSUE THREAD

**Issue by transparentech** [sikachu/sprockets-redirect#12]
I updated my app to rails 4.2.5 which brought in sprockets-rails 3.0.0. Rails.application.assets is now nil by default in production. See this issue:

https://github.com/rails/sprockets-rails/issues/237

This causes sprockets-redirect to throw an "undefined method for nil:NilClass":

```
[2015-12-22 13:40:25] ERROR NoMethodError: undefined method `[]' for nil:NilClass
	/Users/nick/.gem/ruby/2.2.2/gems/sprockets-redirect-0.3.0/lib/sprockets/redirect.rb:64:in `asset_exists?'
	/Users/nick/.gem/ruby/2.2.2/gems/sprockets-redirect-0.3.0/lib/sprockets/redirect.rb:60:in `asset_path_matched?'
	/Users/nick/.gem/ruby/2.2.2/gems/sprockets-redirect-0.3.0/lib/sprockets/redirect.rb:55:in `should_redirect?'
	/Users/nick/.gem/ruby/2.2.2/gems/sprockets-redirect-0.3.0/lib/sprockets/redirect.rb:45:in `call'
	/Users/nick/.gem/ruby/2.2.2/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
	/Users/nick/.gem/ruby/2.2.2/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
	/Users/nick/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/Users/nick/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/nick/.gem/ruby/2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/nick/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/Users/nick/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/Users/nick/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

My workaround was to set `config.assets.compile = true` in `production.rb`, but I'm not sure that's the best or most efficient solution. Would be happy for any other workaround suggestions or official solutions.

**Comment by sikachu** [comment]
Thanks for bringing this issue to my attention. I can take a look later on this week. It looks like we need to fix something to make our gem compatible with sprocket-rails 3.0.0.

**Comment by derekprior** [comment]
See: https://github.com/rails/sprockets-rails/issues/306#issuecomment-169119377 for possible explanation.

**Comment by sikachu** [comment]
This was fixed! I'm going to release v1.0.0 very soon.

**Comment by ericboehs** [comment]
I just ran into this as well. Looking forward to the release.

**Comment by transparentech** [comment]
Update to version 1.0.0, removed my workaround and it works again. Thanks!
